theme: osuny
_merge: deep
params:
  summary:
    position: content
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'
  home:
    head:
      title: site

  projects:
    index:
      options:
        summary: false
    single:
      meta:
        position: hero
        options:
          year: false
          with_labels: false