theme: osuny
_merge: deep
params:
  summary:
    position: content
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo.svg'
  home:
    head:
      title: site

  breadcrumb:
    position: footer

  components:
    lightbox:
      in_hero:
        disabled: true

  organizations:
    prefer_image_over_logo: true
    single:
      backlinks: true

  posts:
    single:
      meta:
        position: hero
        options:
          with_labels: false

  projects:
    index:
      taxonomies:
        display: true
        layout: inline
      options:
        summary: false
    single:
      meta:
        position: hero
        options:
          year: false
          with_labels: false

  image_sizes:
    sections:
      home:
        hero:
          desktop:  1880
      projects:
        hero:
          desktop:  1880
      pages:
        hero:
          desktop:  1880