[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/projets/2007-piano-czapka-1918/index.html"
to = "/pianos/2007-piano-czapka-1918/"

[[redirects]]
from = "/projets/2013-piano-erard-1/index.html"
to = "/pianos/2013-piano-erard-1862/"

[[redirects]]
from = "/projets/2004-piano-erard/index.html"
to = "/pianos/2004-piano-erard-1926/"

[[redirects]]
from = "/questions-frequentes/index.html"
to = "/univers-du-piano/questions-frequentes/"

[[redirects]]
from = "/attrapes/index.html"
to = "/lexique-sur-le-piano/attrapes/"

[[redirects]]
from = "/projets/2007-piano-czapka/index.html"
to = "/pianos/2007-piano-czapka-1918/"

[[redirects]]
from = "/projets/2007-piano-bechstein-1/index.html"
to = "/pianos/2007-piano-bechstein-1910/"

[[redirects]]
from = "/projets/a-vendre/index.html"
to = "/pianos/a-vendre/"

[[redirects]]
from = "/projets/2009-piano-erard-1918/index.html"
to = "/pianos/2009-piano-erard-1918/"

[[redirects]]
from = "/projets/2025-piano-gaveau/index.html"
to = "/pianos/2025-piano-gaveau-1932/"

[[redirects]]
from = "/projets/index.html"
to = "/pianos/"

[[redirects]]
from = "/projets/2008-piano-bechstein-1930/index.html"
to = "/pianos/2008-piano-bechstein-1930/"

[[redirects]]
from = "/actualites/articles/index.html"
to = "/actualites/article/"

[[redirects]]
from = "/projets/2009-piano-erard-2/index.html"
to = "/pianos/2009-piano-erard-1918/"

[[redirects]]
from = "/projets/vendu/index.html"
to = "/pianos/vendu/"

[[redirects]]
from = "/organisations/categories/marques/index.html"
to = "/organisations/categories/manufactures/"

[[redirects]]
from = "/projets/2025-piano-pleyel-1927/index.html"
to = "/pianos/2025-piano-pleyel-1927/"

[[redirects]]
from = "/les-livres-sur-le-piano/index.html"
to = "/univers-du-piano/les-livres-sur-le-piano/"

[[redirects]]
from = "/projets/2008-piano-bechstein/index.html"
to = "/pianos/2008-piano-bechstein-1930/"

[[redirects]]
from = "/projets/2007-piano-bechstein-1910/index.html"
to = "/pianos/2007-piano-bechstein-1910/"

[[redirects]]
from = "/projets/2025-piano-gaveau-1932/index.html"
to = "/pianos/2025-piano-gaveau-1932/"

[[redirects]]
from = "/actualites/2025-01-01-sylvie-fouanon-restauratrice-de-pianos-anciens-a-paris/index.html"
to = "/actualites/2025-06-01-sylvie-fouanon-restauratrice-de-pianos-anciens-a-paris/"

[[redirects]]
from = "/projets/2025-piano-pleyel/index.html"
to = "/pianos/2025-piano-pleyel-1927/"

[[redirects]]
from = "/projets/2004-piano-erard-1926/index.html"
to = "/pianos/2004-piano-erard-1926/"

[[redirects]]
from = "/projets/2013-piano-erard-1862/index.html"
to = "/pianos/2013-piano-erard-1862/"

[[redirects]]
from = "/lexique-sur-le-piano/index.html"
to = "/univers-du-piano/lexique-sur-le-piano/"

